# Generated by Django 4.2.6 on 2023-10-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_alter_formsubmission_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6),
        ),
    ]
