# Generated by Django 4.2.6 on 2023-10-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_alter_formsubmission_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='materials_provide',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='material',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.material'),
        ),
    ]
